// AUTO-GENERATED by scripts/generate-announcement-manifest.mjs — do not edit by hand.
// Regenerated from public/img/announcements/ on every dev start / build (see
// predev/prebuild in package.json and buildCommand in vercel.json). Adding a
// new banner image is now just: drop the file in that folder and commit —
// no manual manifest edit needed.

export interface AnnouncementImageOption {
  filename: string
  path:     string
}

export const ANNOUNCEMENT_IMAGE_OPTIONS: AnnouncementImageOption[] = [
  { filename: "chatroom-update-v1.svg", path: "/img/announcements/chatroom-update-v1.svg" },
  { filename: "messageBubble_react_doubletap.svg", path: "/img/announcements/messageBubble_react_doubletap.svg" },
  { filename: "text-effects-v1.svg", path: "/img/announcements/text-effects-v1.svg" },
]
